<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SiteOptions {
	private $site_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'site_options_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'site_options_page_init' ) );
	}

	public function site_options_add_plugin_page() {
		add_menu_page(
			'Site Options', // page_title
			'Site Options', // menu_title
			'manage_options', // capability
			'site-options', // menu_slug
			array( $this, 'site_options_create_admin_page' ), // function
			'dashicons-index-card', // icon_url
			20 // position
		);
	}

	public function site_options_create_admin_page() {
		$this->site_options = get_option( 'site_option_name' ); ?>
		<style>h2 { font-size: 18px }</style>
		<div class="wrap">
			<h1>Site Options</h1>
			<p>Modify general site info. You can access these fields in any post by using the shortcodes provided at the bottom of this settings page.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'site_option_group' );
					do_settings_sections( 'site-options-admin' );
					submit_button();
				?>
			</form>
			<h2>Shortcodes</h2>
			<ul>
				<li><b>[address_link count="3" link="false"]</b> for an address link. Use <i>link="false"</i> to remove link code. Use <i>count="3"</i> to show only certain parts of the address.</li>
				<li><b>[phone_link]</b> for tel link</li>
				<li><b>[service_time]</b> for raw service time</li>
				<li><b>[file_link text="" classes=""]</b> for a file link</li>
				<li><b>[hours_table]</b> to display the full hours table</li>
			</ul>
		</div>
	<?php }

	public function site_options_page_init() {
		register_setting(
			'site_option_group', // option_group
			'site_option_name', // option_name
			array( $this, 'site_options_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'site_options_setting_section_info', // id
			'Info', // title
			array( $this, 'site_options_section_info' ), // callback
			'site-options-admin' // page
		);

		add_settings_field(
			'address_0', // id
			'Address', // title
			array( $this, 'address_0_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_info' // section
		);

		add_settings_field(
			'phone_1', // id
			'Phone', // title
			array( $this, 'phone_1_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_info' // section
		);

		add_settings_field(
			'service_time_2', // id
			'Service Time', // title
			array( $this, 'service_time_2_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_info' // section
		);

		add_settings_section(
			'site_options_setting_section_cta', // id
			'CTA Link', // title
			array( $this, 'site_options_section_cta' ), // callback
			'site-options-admin' // page
		);

		add_settings_field(
			'cta_text_3', // id
			'CTA Text', // title
			array( $this, 'cta_text_3_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_cta' // section
		);

		add_settings_field(
			'cta_link_4', // id
			'CTA Link', // title
			array( $this, 'cta_link_4_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_cta' // section
		);

		add_settings_section(
			'site_options_setting_section_extras', // id
			'Extras', // title
			array( $this, 'site_options_section_extras' ), // callback
			'site-options-admin' // page
		);

		add_settings_field(
			'file_url_5', // id
			'File URL', // title
			array( $this, 'file_url_5_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_extras' // section
		);

		add_settings_field(
			'footer_column_6', // id
			'Footer Column', // title
			array( $this, 'footer_column_6_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_extras' // section
		);

		// Hours

		add_settings_section(
			'site_options_setting_section_hours', // id
			'Hours', // title
			array( $this, 'site_options_section_hours' ), // callback
			'site-options-admin' // page
		);

		add_settings_field(
			'monday_hours', // id
			'Monday', // title
			array( $this, 'monday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'tuesday_hours', // id
			'Tuesday', // title
			array( $this, 'tuesday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'wednesday_hours', // id
			'Wednesday', // title
			array( $this, 'wednesday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'thursday_hours', // id
			'Thursday', // title
			array( $this, 'thursday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'friday_hours', // id
			'Friday', // title
			array( $this, 'friday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'saturday_hours', // id
			'Saturday', // title
			array( $this, 'saturday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);

		add_settings_field(
			'sunday_hours', // id
			'Sunday', // title
			array( $this, 'sunday_hours_callback' ), // callback
			'site-options-admin', // page
			'site_options_setting_section_hours' // section
		);
	}

	public function site_options_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['address_0'] ) ) {
			$sanitary_values['address_0'] = sanitize_text_field( $input['address_0'] );
		}

		if ( isset( $input['phone_1'] ) ) {
			$sanitary_values['phone_1'] = sanitize_text_field( $input['phone_1'] );
		}

		if ( isset( $input['service_time_2'] ) ) {
			$sanitary_values['service_time_2'] = sanitize_text_field( $input['service_time_2'] );
		}

		if ( isset( $input['cta_text_3'] ) ) {
			$sanitary_values['cta_text_3'] = $input['cta_text_3'];
		}

		if ( isset( $input['cta_link_4'] ) ) {
			$sanitary_values['cta_link_4'] = sanitize_text_field( $input['cta_link_4'] );
		}

		if ( isset( $input['file_url_5'] ) ) {
			$sanitary_values['file_url_5'] = sanitize_text_field( $input['file_url_5'] );
		}

		if ( isset( $input['footer_column_6'] ) ) {
			$sanitary_values['footer_column_6'] = $input['footer_column_6'];
		}

		//hours

		if ( isset( $input['monday_hours_open'] ) ) {
			$sanitary_values['monday_hours_open'] = $input['monday_hours_open'];
		}

		if ( isset( $input['monday_hours_close'] ) ) {
			$sanitary_values['monday_hours_close'] = $input['monday_hours_close'];
		}

		if ( isset( $input['tuesday_hours_open'] ) ) {
			$sanitary_values['tuesday_hours_open'] = $input['tuesday_hours_open'];
		}

		if ( isset( $input['tuesday_hours_close'] ) ) {
			$sanitary_values['tuesday_hours_close'] = $input['tuesday_hours_close'];
		}

		if ( isset( $input['wednesday_hours_open'] ) ) {
			$sanitary_values['wednesday_hours_open'] = $input['wednesday_hours_open'];
		}

		if ( isset( $input['wednesday_hours_close'] ) ) {
			$sanitary_values['wednesday_hours_close'] = $input['wednesday_hours_close'];
		}

		if ( isset( $input['thursday_hours_open'] ) ) {
			$sanitary_values['thursday_hours_open'] = $input['thursday_hours_open'];
		}

		if ( isset( $input['thursday_hours_close'] ) ) {
			$sanitary_values['thursday_hours_close'] = $input['thursday_hours_close'];
		}

		if ( isset( $input['friday_hours_open'] ) ) {
			$sanitary_values['friday_hours_open'] = $input['friday_hours_open'];
		}

		if ( isset( $input['friday_hours_close'] ) ) {
			$sanitary_values['friday_hours_close'] = $input['friday_hours_close'];
		}

		if ( isset( $input['saturday_hours_open'] ) ) {
			$sanitary_values['saturday_hours_open'] = $input['saturday_hours_open'];
		}

		if ( isset( $input['saturday_hours_close'] ) ) {
			$sanitary_values['saturday_hours_close'] = $input['saturday_hours_close'];
		}

		if ( isset( $input['sunday_hours_open'] ) ) {
			$sanitary_values['sunday_hours_open'] = $input['sunday_hours_open'];
		}

		if ( isset( $input['sunday_hours_close'] ) ) {
			$sanitary_values['sunday_hours_close'] = $input['sunday_hours_close'];
		}

		return $sanitary_values;
	}

	public function site_options_section_info() {
		?><hr><?php
	}

	public function address_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[address_0]" id="address_0" value="%s">',
			isset( $this->site_options['address_0'] ) ? esc_attr( $this->site_options['address_0']) : ''
		);
	}

	public function phone_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[phone_1]" id="phone_1" value="%s">',
			isset( $this->site_options['phone_1'] ) ? esc_attr( $this->site_options['phone_1']) : ''
		);
	}

	public function service_time_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[service_time_2]" id="service_time_2" value="%s">',
			isset( $this->site_options['service_time_2'] ) ? esc_attr( $this->site_options['service_time_2']) : ''
		);
	}

	public function site_options_section_cta() {
		?><hr><?php
	}

	public function cta_text_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[cta_text_3]" id="cta_text_3" value="%s">',
			isset( $this->site_options['cta_text_3'] ) ? esc_attr( $this->site_options['cta_text_3']) : ''
		);
	}

	public function cta_link_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[cta_link_4]" id="cta_link_4" value="%s">',
			isset( $this->site_options['cta_link_4'] ) ? esc_attr( $this->site_options['cta_link_4']) : ''
		);
	}

	public function site_options_section_extras() {
		?><hr><?php
	}

	public function file_url_5_callback() {
		?>

		<?php
		// jQuery
		wp_enqueue_script('jquery');
		// This will enqueue the Media Uploader script
		wp_enqueue_media();
		?>
		<div>
			<input type="text" class="regular-text" name="site_option_name[file_url_5]" id="file_url_5" value="<?php echo isset( $this->site_options['file_url_5'] ) ? esc_attr( $this->site_options['file_url_5']) : '' ?>">
			<input type="button" name="upload-btn" id="upload-btn" class="button-secondary" value="Choose File">
		</div>
		<!-- JS to enable the WP Media uploader -->
		<script type="text/javascript">
			jQuery(document).ready(function($){
				$('#upload-btn').click(function(e) { // Target the button
					e.preventDefault();
					var image = wp.media({ 
						title: 'Choose File',
						// mutiple: true if you want to upload multiple files at once
						multiple: false
					}).open()
					.on('select', function(e){
						// This will return the selected image from the Media Uploader, the result is an object
						var uploaded_image = image.state().get('selection').first();
						// We convert uploaded_image to a JSON object to make accessing it easier
						// Output to the console uploaded_image
						console.log(uploaded_image);
						var image_url = uploaded_image.toJSON().url;
						// Let's assign the url value to the input field
						$('#file_url_5').val(image_url); // Target the input
					});
				});
			});
		</script>
		<?php
	}

	public function footer_column_6_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="site_option_name[footer_column_6]" id="footer_column_6">%s</textarea>',
			isset( $this->site_options['footer_column_6'] ) ? esc_attr( $this->site_options['footer_column_6']) : ''
		);
	}

	// Hours

	public function site_options_section_hours() {
		?><hr><?php
	}

	public function monday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[monday_hours_open]" id="monday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['monday_hours_open'] ) ? esc_attr( $this->site_options['monday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[monday_hours_close]" id="monday_hours_close" value="%s">',
			isset( $this->site_options['monday_hours_close'] ) ? esc_attr( $this->site_options['monday_hours_close']) : ''
		);
	}

	public function tuesday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[tuesday_hours_open]" id="tuesday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['tuesday_hours_open'] ) ? esc_attr( $this->site_options['tuesday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[tuesday_hours_close]" id="tuesday_hours_close" value="%s">',
			isset( $this->site_options['tuesday_hours_close'] ) ? esc_attr( $this->site_options['tuesday_hours_close']) : ''
		);
	}

	public function wednesday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[wednesday_hours_open]" id="wednesday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['wednesday_hours_open'] ) ? esc_attr( $this->site_options['wednesday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[wednesday_hours_close]" id="wednesday_hours_close" value="%s">',
			isset( $this->site_options['wednesday_hours_close'] ) ? esc_attr( $this->site_options['wednesday_hours_close']) : ''
		);
	}

	public function thursday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[thursday_hours_open]" id="thursday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['thursday_hours_open'] ) ? esc_attr( $this->site_options['thursday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[thursday_hours_close]" id="thursday_hours_close" value="%s">',
			isset( $this->site_options['thursday_hours_close'] ) ? esc_attr( $this->site_options['thursday_hours_close']) : ''
		);
	}

	public function friday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[friday_hours_open]" id="friday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['friday_hours_open'] ) ? esc_attr( $this->site_options['friday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[friday_hours_close]" id="friday_hours_close" value="%s">',
			isset( $this->site_options['friday_hours_close'] ) ? esc_attr( $this->site_options['friday_hours_close']) : ''
		);
	}

	public function saturday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[saturday_hours_open]" id="saturday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['saturday_hours_open'] ) ? esc_attr( $this->site_options['saturday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[saturday_hours_close]" id="saturday_hours_close" value="%s">',
			isset( $this->site_options['saturday_hours_close'] ) ? esc_attr( $this->site_options['saturday_hours_close']) : ''
		);
	}

	public function sunday_hours_callback() {
		printf(
			'<input class="regular-text" type="text" name="site_option_name[sunday_hours_open]" id="sunday_hours_open" value="%s" style="margin-right: 1em;">',
			isset( $this->site_options['sunday_hours_open'] ) ? esc_attr( $this->site_options['sunday_hours_open']) : ''
		);
		printf(
			'<input class="regular-text" type="text" name="site_option_name[sunday_hours_close]" id="sunday_hours_close" value="%s">',
			isset( $this->site_options['sunday_hours_close'] ) ? esc_attr( $this->site_options['sunday_hours_close']) : ''
		);
	}

}
if ( is_admin() )
	$site_options = new SiteOptions();

/* 
 * Retrieve this value with:
 * $site_options = get_option( 'site_option_name' ) ['address_0']; // Array of All Options
 * $address_0 = $site_options['address_0']; // Address
 * $phone_1 = $site_options['phone_1']; // Phone
 * $service_time_2 = $site_options['service_time_2']; // Service Time
 * $cta_text_3 = $site_options['cta_text_3']; // CTA Text
 * $cta_link_4 = $site_options['cta_link_4']; // CTA Link
 * $file_url_5 = $site_options['file_url_5']; // File URL
 * $footer_column_6 = $site_options['footer_column_6']; // Footer Column
 */
